# Generated by Django 5.1.4 on 2024-12-20 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediascore', '0002_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='appNames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='screenShot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
